# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, default='default.png', upload_to=b'')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
